name: Download and Commit Stable Diffusion Model Checkpoint

on:
  push:
    branches:
      - main  # Trigger when there is a push to the 'main' branch
  workflow_dispatch:  # Allows manual triggering of this workflow

jobs:
  download_and_push:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Git LFS
    - name: Set up Git LFS
      run: |
        git lfs install  # Install Git LFS on the runner

    # Step 3: Download the model file (optional, if you're downloading a file from a URL)
    - name: Download Stable Diffusion Model Checkpoint
      run: |
        wget -O model_data/sd-v1-4.ckpt https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt

    # Step 4: Configure Git
    - name: Configure Git
      run: |
        git config --global user.name "SaltyBot"
        git config --global user.email "actions@github.com"

    # Step 5: Commit the model file using Git LFS
    - name: Commit and push model file with Git LFS
      run: |
        git add model_data/sd-v1-4.ckpt
        git commit -m "Add stable diffusion model checkpoint"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
